Patch 2
HamStudy/examtools-docs pull request #39
Opened 2021-04-28 23:15 UTC by hparkersd

Added in-person sessions and also a supporting page for the VE List.  I can only see MarkDown so I will need to edit these again.  I also need to figure out how to add a few images.

2021-04-29 18:49 UTC, n2ygk requested changes
I believe you wanted to add screen shots as well. These go in https://github.com/HamStudy/examtools-docs/tree/master/content/docs/cve/images as png or jpeg files and then you reference them. See some existing pages with screenshots for examples.

2021-04-29 18:49 UTC, n2ygk commented on content/docs/cve/cveIn-PersonExamProcess
> +---
I think you need to add a reference to this page in https://github.com/HamStudy/examtools-docs/blob/master/content/docs/cve/_index.md and maybe also https://github.com/HamStudy/examtools-docs/blob/master/content/docs/_index.md

2021-04-29 18:49 UTC, n2ygk commented on content/docs/cve/cveVEList
> +---
As above, references to this page after to be added in the `_index.md` files.

2021-04-30 04:31 UTC, hparkersd commented
I am at a stopping point.

2021-05-01 14:08 UTC, n2ygk commented
> I am at a stopping point.

Are you ready for my review? I see you've just pushed some more...

2021-05-01 14:11 UTC, hparkersd commented
> I believe you wanted to add screen shots as well. These go in https://github.com/HamStudy/examtools-docs/tree/master/content/docs/cve/images as png or jpeg files and then you reference them. See some existing pages with screenshots for examples.

I added an image.  That is all I have right now, but understand how to do it.

2021-05-01 14:38 UTC, merged

2021-05-01 14:39 UTC, n2ygk commented
@hparkersd I made a couple of small fixes:
- replaced http: with https:
- replaced "hard coded" refs to docs.exam.tools with relrefs.

2021-05-01 14:54 UTC, hparkersd commented
Thanks!  I was not able to get them to work in my new pages.  Was missing something.