initial W5YI ocs
HamStudy/examtools-docs pull request #60
Opened 2022-01-18 20:33 UTC by ARBatteiger

Initial W5YI Documentation

2022-01-18 20:46 UTC, n2ygk requested changes
Hey nice. Thanks for this.

You need to add links to make this findable to content/docs/_index.md

You can see what the site would look like by clicking on the "deploy preview" link in Checks.

2022-01-18 20:50 UTC, n2ygk requested changes

2022-01-18 20:50 UTC, n2ygk commented on content/docs/w5yi/_index.md
> +![W5YI](images/logo.jpg)
```suggestion
![W5YI](images/veclogo.jpg)
```

2022-01-18 23:08 UTC, ARBatteiger commented
for some reason the files do not look like what I have here.   They look like the original ARRL files.    I am not sure what step I missed.   I did a pull, then updated the files, the a git add, git commit, git push.    Then generated the pull request

2022-01-18 23:12 UTC, ARBatteiger commented
looks like I need to refresh to pick up changes.   I need to fix a couple of links.  Also I added the W5YI to the main _index.md but I do not see the change in the deploy preview

2022-01-19 00:16 UTC, n2ygk commented
> looks like I need to refresh to pick up changes.   I need to fix a couple of links.  Also I added the W5YI to the main _index.md but I do not see the change in the deploy preview
> 
> 

See failed checks. Looks like an incorrect `ref`. 

I am not a fan of this website generator....

2022-01-19 01:58 UTC, ARBatteiger commented
Lets try again the logo image was missing

2022-01-19 15:32 UTC, n2ygk requested changes
See review comments and suggestions.

Hint (something I recently learned) about [batching accepted suggestions](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request#applying-suggested-changes)

2022-01-19 15:32 UTC, n2ygk commented on content/docs/_index.md.bak
> +---
oops, you committed this backup file. Please `git rm` it and push another commit.

2022-01-19 15:32 UTC, n2ygk commented on content/docs/w5yi/_index.md
> +used by the [AA7HW VE Team] for some ideas. As with in-person sessions, there's always room for customizing how your particular team operates.
```suggestion
used by the [AA7HW VE Team](https://aa7hw.org/) for some ideas. As with in-person sessions, there's always room for customizing how your particular team operates.
```

2022-01-19 15:32 UTC, n2ygk commented on content/docs/w5yi/greeter-script.md
> +W5YI VE SCRIPT 1
Formatting is not working below. You need to replace the bullet characters with asterisks.

2022-01-19 15:58 UTC, ARBatteiger commented
changes made, I tried to create a new pull request, but it said no differences ?

2022-01-19 16:07 UTC, n2ygk requested changes
Very close. Just one or two minor nits and we should be good to go on the next round.

2022-01-19 16:07 UTC, n2ygk commented on .gitignore.bak
> +# IDEs
haha oops you committed .gitignore.bak ;-)

2022-01-19 16:07 UTC, n2ygk commented on content/docs/w5yi/greeter-script.md
> +o Is ID acceptable to all VE’s?
Presumably these `o` characters here and below are meant to be sub-bullets? You'll want to use asterisk indented.
```suggestion
  * Is ID acceptable to all VE’s?
```

2022-01-19 16:07 UTC, n2ygk commented on content/docs/w5yi/checklist.md
> +  `ExamSession_{Callsign)_YYYYMMDD_HHMM.pdf`
Open curly, close paren:
```suggestion
  `ExamSession_(Callsign)_YYYYMMDD_HHMM.pdf`
```

2022-01-19 17:58 UTC, merged