Hparkersd patch 1
HamStudy/examtools-docs pull request #74
Opened 2023-08-03 17:50 UTC by hparkersd

Updates related to teams

2023-08-03 20:47 UTC, n2ygk approved these changes

2023-08-03 20:48 UTC, n2ygk commented
@hparkersd is this still a draft? Please remove the draft status if you are ready

2023-08-03 21:43 UTC, hparkersd commented
> @hparkersd is this still a draft? Please remove the draft status if you are ready

I am still working on it.  I needed to stop for the day.

2023-08-04 14:47 UTC, hparkersd commented
I am ready to go.  Will refrain from tinkering with it.

2023-08-07 13:02 UTC, n2ygk requested changes
I did a pretty cursory review this time. Perhaps ask one or two others to look at the content on the [draft site](https://deploy-preview-74--examtools-docs.netlify.app/).

2023-08-07 18:54 UTC, n2ygk requested changes
Wow, @hparkersd, a ton of improvements. I've made a few suggestions which you can "add to batch" and then apply if you agree with them. Some where stuff you didn't touch on this time around but that I noticed while viewing the rendered docs (at https://deploy-preview-74--examtools-docs.netlify.app/docs/).

2023-08-07 18:54 UTC, n2ygk commented on content/docs/cve/Zoom.md
> +
```suggestion
The ARRL/VEC and others have asked that we not record candidate sessions. If you choose to record, be certain to *never record personally-identifiable information (PII)* such as photo ID and only record if the applicant has given explicit permission to do so.
```

2023-08-07 18:54 UTC, n2ygk commented on content/docs/cve/cveTeams.md
>  ## Intro:
```suggestion
## Introduction
```

2023-08-07 18:54 UTC, n2ygk commented on content/docs/cve/cveTeams.md
>  ## Create a New Team Account:
```suggestion
## Create a New Team Account
```

2023-08-07 18:54 UTC, n2ygk commented on content/docs/cve/cveVEList.md
> +## Add a Volunteer Examiner (VE) to an Exam Session:
```suggestion
## Add a Volunteer Examiner (VE) to an Exam Session
```

2023-08-07 18:54 UTC, n2ygk commented on content/docs/cve/cveVEList.md
> +> **Required on a New Session Listing:**  If you see "You are not part of this session" on a gold alert ribbon when you first access the session listing, make sure to click the **JOIN** button from t
Did you intend this to be a quoted block?
```suggestion
**Required on a New Session Listing:**  If you see "You are not part of this session" on a gold alert ribbon when you first access the session listing, make sure to click the **JOIN** button from the Applicant Tab. Next, click on the Volunteer Examiner tab. If fail to join the session, you will see that the session has 0 VEs and a blue box with "No Volunteer Examiners have been added to the session". Return back to the gold ribbon on the Applicant Tab and click the **JOIN** button. Then, click on the Volunteer Examiner tab.  You must then change your permissions to co-owner in order to add the rest of your team.
```

2023-08-07 18:54 UTC, n2ygk commented on content/docs/cve/printedExamCreation.md
>  Follow these instructions to print out randomly generated exams for use with a manual grading key
```suggestion
Follow these instructions to print out randomly generated exams for use with a manual grading key:
```

2023-08-07 18:54 UTC, n2ygk commented on content/docs/cve/printedExamCreation.md
>  * The default selection is **Manual Grading**, indicated by a grey highlight
```suggestion
* The default selection is **Manual Grading**, indicated by a grey highlight.
```

2023-08-08 13:07 UTC, merged